version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./src/main/resources/players.json:/app/players.json"
    environment:
      - PLAYERS_JSON_PATH=/app/players.json
